security:
    providers:
        localusers:
            entity: { class: FourxxiTestJobBundle:User, property: username }
        hwi:                               
            id: hwi_oauth.user.provider.entity
    encoders:
        Fourxxi\TestJobBundle\Entity\User: plaintext
        HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUser: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
    access_control:
        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/newuser,        roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect,        roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: IS_AUTHENTICATED_FULLY }
