security:
    providers:
        administrators:
            entity: { class: FourxxiTestJobBundle:User, property: username }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Fourxxi\TestJobBundle\Entity\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,               roles: IS_AUTHENTICATED_FULLY }
