security:
    providers:
        administrators:
            entity: { class: FourxxiTestJobBundle:User, property: username }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Fourxxi\TestJobBundle\Entity\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check